Repository GSG-G11/Book-library, pull requests merged in 2022-03, with the labels that each got.

#2 Create File Structure #1
  .gitignore
  Public/Css/Style.css
  Public/Html/index.html
  Public/Js/index.js
  Server/Contorllers/index.js
  Server/Database/build.js
  Server/Database/build.sql
  Server/Routes/index.js
  Server/Test/test.js
  package-lock.json
  package.json
Labels: Awaiting Review

#4 Create Add book Page
  Public/addbook.html
  Public/index.html
Labels: Done

#6 Create Server
  Public/Html/404.html
  Public/Html/500.html
  src/app.js
  src/controllers/addbook.js
  src/controllers/error.js
  src/controllers/index.js
  src/index.js
  src/routes/route.js
  src/test/test.js
Labels: Done

#12 Add book db js
  Public/Css/indexStyle.css
  Public/addbook.html
  src/controllers/addbook.js
  src/database/config/build.sql
  src/database/config/build_test.sql
  src/database/config/connection.js
  src/database/queries/addbookDB.js
Labels: Awaiting Review

#14 Update Json #11
  package.json
Labels: Approved

#17 16 fix typo
  .eslintrc.json
  Public/Js/index.js
  Public/index.html
  package-lock.json
  package.json
  src/controllers/addbook.js
  src/controllers/getbook.js
  src/controllers/index.js
  src/database/config/connection.js
  src/database/queries/addbookDB.js
  src/database/queries/getbookDB.js
  src/index.js
  src/routes/route.js
Labels: Done, Approved

#20 Create get book
  src/controllers/getbook.js
  src/database/queries/getbookDB.js
Labels: Approved

#23 update dom
  Public/Js/index.js
  Public/addbook.html
  Public/index.html
  package.json
  src/database/config/build_test.sql
Labels: Approved

#26 mylibrary
  Public/Css/library.css
  Public/Css/myLibrary.css
  Public/myLibrary.html
Labels: Approved

#31 Create Delete
  Public/Js/mybooks.js
Labels: Approved

#32 update index
  Public/Css/Style.css
  Public/index.html
  Public/myLibrary.html
Labels: Awaiting Review

#34 update index
  Public/Css/Style.css
  Public/Css/indexStyle.css
  Public/Css/mybookStyle.css
  Public/Js/index.js
  Public/Js/mybooks.js
  Public/index.html
  src/controllers/addMyBook.js
  src/controllers/index.js
  src/database/config/build_test.sql
  src/database/queries/addMyBookDB.js
  src/routes/route.js
Labels: Approved

#36 Final Touch
  Public/Css/library.css
  Public/Css/myLibrary.css
  Public/Js/index.js
  package.json
  src/app.js
  src/controllers/index.js
  src/database/config/build.js
  src/database/config/connection.js
Labels: Awaiting Review

#38 add test
  src/controllers/index.js
  src/test/test.js
Labels: Awaiting Review

#40 Fix Issues
  Public/Css/Style.css
  Public/Css/indexStyle.css
  Public/Js/index.js
  Public/addbook.html
  Public/index.html
  Public/mybooks.html
  README.md
  src/controllers/deletemybook.js
  src/controllers/index.js
  src/database/config/connection.js
  src/database/queries/deletemybook.js
  src/routes/route.js
Labels: Approved

#42 create readme
  README.md
Labels: Approved
